require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'traceApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'


  pod 'GoogleSignIn', '~> 5.0.2'

  pod 'RNSoundPlayer', :path => '../node_modules/react-native-sound-player'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'traceAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'traceApp-tvOS' do
  # Pods for traceapp-tvOS

  target 'traceApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
